using System;

namespace Fido2NetLib.Objects
{
    public sealed class AttestationConveyancePreference : TypedString
    {
        /// <summary>
        /// This value indicates that the Relying Party is not interested in authenticator attestation. For example, in order to potentially avoid having to obtain user consent to relay identifying information to the Relying Party, or to save a roundtrip to an Attestation CA.
        /// This is the default value.
        /// </summary>
        public static readonly AttestationConveyancePreference None = new AttestationConveyancePreference("none");
        /// <summary>
        /// This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation statements, but allows the client to decide how to obtain such attestation statements. The client MAY replace the authenticator-generated attestation statements with attestation statements generated by an Anonymization CA, in order to protect the user’s privacy, or to assist Relying Parties with attestation verification in a heterogeneous ecosystem.
        /// </summary>
        public static readonly AttestationConveyancePreference Indirect = new AttestationConveyancePreference("indirect");

        /// <summary>
        /// This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
        /// </summary>
        public static readonly AttestationConveyancePreference Direct = new AttestationConveyancePreference("direct");

        
        private AttestationConveyancePreference(string value) : base(value)
        {
        }

        public static AttestationConveyancePreference Parse(string value)
        {
            switch (value)
            {
                case "none":
                    return None;
                case "indirect":
                    return Indirect;
                case "direct":
                    return Direct;
                default:
                    throw new InvalidOperationException("Could not parse value");
            }
        }
    }
}
